### ISSUE TITLE
Can't locate Text/Balanced.pm in @INC

### ISSUE THREAD

**Issue by Wu-tz** [hewm2008/NGenomeSyn#1]
I have installed Text::Balanced model, but it is still so. What can I do to result it？

**Comment by hewm2008** [comment]
find the path of [Text/Balanced.pm] , as  /path/xxxx/yyy/Text/Balanced.pm 
method 1 :  
you can    
export PERL5LIB= /path/xxxx/yyy:$PERL5LIB   
and run it

method 2 : 
cp -r      /path/xxxx/yyy/Text       NGenomeSyn-xxx/bin/svg_kit


you can join the QQ group :125293663
