### ISSUE TITLE
input files 

### ISSUE THREAD

**Issue by xbarvazx** [hewm2008/NGenomeSyn#11]
Hi,

I get these errors when running the config file as in example 1 with my two genome data.
Is it a problem for chromosomes to be labelled  'chr1A'?

`Argument "chr1" isn't numeric in subtraction (-) at ../../progrems/NGenomeSyn/bin/NGenomeSyn line 1563, <INData> line 1.`

`Warning : at Link File ngenomesyn_sorted.link can't find the chr 754798 at the  the 2 Genome File info`

Thanks,

**Comment by hewm2008** [comment]
you can head the input file here   (ngenomesyn_sorted.link   GenomeA.len  GenomeB.len)
I guess you can try switch the [  GenomeA.len  GenomeB.len ]

**Comment by xbarvazx** [comment]
Thanks, it was a silly mistake as I included the line numbering as a
column...

**Comment by hewm2008** [comment]
you can sent your   [ len link  confi] file to me by hewm2008@gmail.com
