### ISSUE TITLE
Parameters 

### ISSUE THREAD

**Issue by xbarvazx** [hewm2008/NGenomeSyn#12]
Hi,

I have an inversion on one chromosome that I would like to highlight.
I added 
`fill=red        stroke=red`
But it is shown behind the other lines and I would like it to be above the other lines?

Second question, how can I get the bottom chromosome names to be under the chromosome banner and not inside it?

Thanks,

**Comment by hewm2008** [comment]
yes,  you can  remove   [this chr link  line  ] to the end of   link. file
