### ISSUE TITLE
请问怎么让染色体片段不描边，只填充颜色

### ISSUE THREAD

**Issue by z626093820** [hewm2008/NGenomeSyn#13]
我在配置文件加了stroke-width=0，好像不起作用，谢谢您！

#设置所有基因组的默认参数
SetParaFor = GenomeALL  ## GenomeALL/GenomeX : setting parameter  for the ALL/1st genome
ChrNameShow=1
stroke-width=0
#ZoomChr=1        ## enlarge(>1) or reduce(<1) or equal (=1) the lenghth of chromosomes，chr 长度 等大 缩小 or 扩大
#RotateChr=30         ##  rotation angles for the chromosomes with clockwise(>0) or counterclockwise(<0) chr 的起点 顺时针 旋转 xx 度
#ShiftX=0
#ShiftY=0             ## move this genome 对这个基因组移动
#MoveToX/Y	##直接移动到指定的点

**Comment by z626093820** [comment]
stroke-width=0是起作用的

**Comment by hewm2008** [comment]
解决了就行     有问题再联系。by the way 同时可以把 stroke = green  fill=green也可以调为fill同为颜色
