### ISSUE TITLE
Genome labels for >10 genomes?

### ISSUE THREAD

**Issue by lcoombe** [hewm2008/NGenomeSyn#14]
Hello,

I was trying to visualize >10 genome assemblies with your tool, but the genome labels (on the left side) are only showing up for the first 8 genomes? Is there anything I need to specify in the conf file to ensure that all genomes have labels?

I am using v1.14, and haven't made any changes in the conf file, other than specifying the input len and links files.

Thanks!
Lauren

**Comment by lcoombe** [comment]
Update: I can see that the labels are visible in the SVG output, so seems to be related to the conversion from SVG to PNG? So if that isn't an easy fix, I can do that SVG -> PNG conversion independently on my end!

**Comment by hewm2008** [comment]
In this case, there may be a problem with convert in your Linux system. The suggestion is 
1. Update the convert software.  try  convert  xxx.svg xxx.png
2 Directly use svg to open it in windows and use other screenshot software to convert it to png.
