### ISSUE TITLE
有一个小小的建议或者疑问

### ISSUE THREAD

**Issue by wjq1981** [hewm2008/NGenomeSyn#2]
非常感谢开发NGenomeSyn，它非常的好用。
GetTwoGenomeSyn.pl程序的494行$MinAlgLen这里。平常我们都是调试$MinAlgLen，但是当基因组很大的时候只能从头开始运作，这变得很慢。能不能从494行这里设定一个什么，能自动读取493行的paf文件，直接运行后面的步骤，就不用再minimap比对了呢？

**Comment by hewm2008** [comment]
我感觉你这个问题问得有点多余啊
494行的命令   不是写到   $OutPrefix.mapping.sh  的脚里面么？
你只要cat   $OutPrefix.mapping.sh 脚本，第一行  minimap2  前面加个#    第二行  MinAlgLen 修为你要改的参数，然后运行一下  sh    $OutPrefix.mapping.sh   只须要1min不到 就可以直接出图了。
之所以把命令写在      $OutPrefix.mapping.sh  里面 ，就是为了解决你这个问题的。    
所以说说你的问题  是多余的。

**Comment by wjq1981** [comment]
是哦，我傻了，谢谢。
