### ISSUE TITLE
保持序列原来的长度

### ISSUE THREAD

**Issue by zhoudreames** [hewm2008/NGenomeSyn#3]
我使用3个基因组绘制共线性图，但是绘制的图的3个基因组序列的长度都是显示一样长的，然而事实上这三个序列分别1.77Mb, 1.65Mb 和1.65Mb, 怎样更改参数使它们展示原始的长度？
![three](https://github.com/hewm2008/NGenomeSyn/assets/54714639/2508cb99-dfbc-46a9-8ba5-dcf26e6b1bda)

**Comment by zhoudreames** [comment]
@hewm2008 很抱歉打扰您，可以帮忙解答一下吗？谢谢您。

**Comment by hewm2008** [comment]
inconf有说明也，你可以在各个genome里面加个 
NormalizedScale=1     #   不行就用 0
