### ISSUE TITLE
Error occurred during runningGetTwoGenomeSyn.pl  ##line 1589

### ISSUE THREAD

**Issue by yyyuechen** [hewm2008/NGenomeSyn#8]
hello老师好，非常感谢您的团队开发了这个软件，我在尝试的过程中遇到了一个问题，希望可以得到您的指点：
我在装配好环境之后尝试跑了example1并且成功，然后我就用自己的mags开始跑，但是总是遇到这个问题： Error:	InPut Genome Link 1-2 Info easy.link file  Format wrong,pleas check it， 然后我打开了这个file发现是空的，请问有什么可能的原因会造成这个结果呢？ 我的mags都是原核生物， binning完成度均在80%以上

非常感谢！！ 这是我的代码和错误提示：
perl  /ibex/scratch/cheny0r/NGenomeSyn/bin/GetTwoGenomeSyn.pl -InGenomeA  124182.assembled.fasta  -InGenomeB 5_arc_Bathyarchaeia_bin.35.fasta -OutPrefix easy  -MappingBin mummer  -BinDir /ibex/sw/rl9c/mummer/4.0.0/rl9.1_gnu12.2.0/mummer-4.0.0rc1/install/bin/  -MinLenA  5000  -MinLenB 5000

Warining: SVG module in Perl is missing, trying to loading the built-in [SVG.pm]...
Loading SVG module done
Use of uninitialized value $_ in scalar chomp at /ibex/scratch/cheny0r/NGenomeSyn/bin/NGenomeSyn line 1589.
Use of uninitialized value $_ in split at /ibex/scratch/cheny0r/NGenomeSyn/bin/NGenomeSyn line 1589.

Error:	InPut Genome Link 1-2 Info easy.link file  Format wrong,pleas check it
	ALL done, see the xxx.png . you can optimized drawing by [NGenomeSyn] software
	     optimized: [Filter] and [Merge] small syn blocks to big syn block

**Comment by hewm2008** [comment]
A :  物种远  一般用gene 蛋白  比对（blastp diamond 再用mcscan 找共线性块） 
 B :  物种近 ，直接用genome数据分析，（一般是同一个种  不同品种的基因组用 minimap2 mummer找共线性区域  ）   


             你这是两个物种太远了   从dNA没有找到共线性块，建议先用蛋白找到共线性块
