### ISSUE TITLE
error with run2.sh in example1/ directory 

### ISSUE THREAD

**Issue by dillnelson2o** [hewm2008/NGenomeSyn#9]
I get this error when running the script run2.sh my data is in the .fa/.gff format, what type of format data is best to use to start the analysis.

Thank You,

Dillon

<img width="1078" alt="Screenshot 2024-03-05 at 10 42 32 AM" src="https://github.com/hewm2008/NGenomeSyn/assets/77173156/88e798b4-1023-4edb-bc7c-c5fd60466312">

**Comment by hewm2008** [comment]
A: If species are far away, gene protein comparison is generally used (blastp diamond and then mcscan are used to find collinear blocks)
B: The species are close, and genome data analysis is used directly. (Generally, for genomes of the same species and different species, use minimap2 mummer to find collinear regions)

          Your two species are too far apart. No collinear blocks can be found from DNA. It is recommended to use proteins to find collinear blocks first.
